/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2022-09-21 07:48:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>登录页面</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- begin::global styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendors/bundle.css\" type=\"text/css\">\r\n");
      out.write("    <!-- end::global styles -->\r\n");
      out.write("\r\n");
      out.write("    <!-- begin::custom styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/app.css\" type=\"text/css\">\r\n");
      out.write("    <!-- end::custom styles -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-white h-100-vh p-t-0\">\r\n");
      out.write("\r\n");
      out.write("<!-- begin::page loader-->\r\n");
      out.write("<div class=\"page-loader\">\r\n");
      out.write("    <div class=\"spinner-border\"></div>\r\n");
      out.write("    <span>Loading ...</span>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- end::page loader -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"p-b-50 d-block d-lg-none\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container h-100-vh\">\r\n");
      out.write("    <div class=\"row align-items-md-center h-100-vh\">\r\n");
      out.write("        <div class=\"col-lg-6 d-none d-lg-block\">\r\n");
      out.write("            <img class=\"img-fluid\" src=\"assets/media/svg/login.svg\" alt=\"...\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-lg-4 offset-lg-1\">\r\n");
      out.write("            <div class=\"d-flex align-items-center m-b-20\">\r\n");
      out.write("                <img src=\"assets/media/image/dark-logo.png\" class=\"m-r-15\" width=\"40\" alt=\"\">\r\n");
      out.write("                <h3 class=\"m-0\">欢迎使用人事管理系统</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p>当前为管理员系统，请登录</p>\r\n");
      out.write("            <form class=\"form-login\" action=\"AdminLogin\" method=\"post\">\r\n");
      out.write("                <div class=\"form-group mb-4\">\r\n");
      out.write("                    <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"name\" class=\"form-control\" placeholder=\"请输入用户名\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group mb-4\">\r\n");
      out.write("                    <input type=\"password\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"password\" class=\"form-control\" placeholder=\"请输入用户密码\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn btn-primary btn-lg btn-block btn-uppercase mb-4\" type=\"submit\">登录</button>\r\n");
      out.write("                <!-- <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("                    <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\">\r\n");
      out.write("                        <label class=\"custom-control-label\" for=\"customCheck\">Keep me signed in</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"auth-link text-black\">Forgot password?</a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("                <div style=\"text-align:center\">\r\n");
      out.write("                <p style=\"color: red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 mb-4\">                    \r\n");
      out.write("                        <a href=\"http://localhost:8080/Personnel_Management/\" class=\"btn btn-outline-facebook btn-block\">\r\n");
      out.write("                            <i class=\"m-r-5\"></i> 员工登录\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                        <a href=\"\" class=\"btn btn-outline-google btn-block\">\r\n");
      out.write("                            <i class=\"m-r-5\"></i> 管理员登录\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"text-center\">\r\n");
      out.write("                    Don't have an account? <a href=\"register.html\" class=\"text-primary\">Create</a>\r\n");
      out.write("                </div> -->\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- begin::global scripts -->\r\n");
      out.write("<script src=\"assets/vendors/bundle.js\"></script>\r\n");
      out.write("<!-- end::global scripts -->\r\n");
      out.write("\r\n");
      out.write("<!-- begin::custom scripts -->\r\n");
      out.write("<script src=\"assets/js/app.js\"></script>\r\n");
      out.write("<!-- end::custom scripts -->\r\n");
      out.write("\r\n");
      out.write("<!-- js placed at the end of the document so the pages load faster -->\r\n");
      out.write("<script src=\"assets/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
