/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2022-09-30 08:02:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gec.entity.Message;
import java.util.*;
import java.text.*;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public final class Emp_005fInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/yueqian/作业/第二阶段项目/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Personnel_Management/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/yueqian/作业/第二阶段项目/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Personnel_Management/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1663657070368L));
    _jspx_dependants.put("jar:file:/D:/yueqian/作业/第二阶段项目/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Personnel_Management/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpServletRequest");
    _jspx_imports_classes.add("javax.servlet.http.HttpServletResponse");
    _jspx_imports_classes.add("com.gec.entity.Message");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 加入taglib的声明 prefix：前缀  uri：加载的库-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>管理员首页</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- begin::global styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/bundle.css\" type=\"text/css\">\r\n");
      out.write("<!-- end::global styles -->\r\n");
      out.write("\r\n");
      out.write("<!-- begin::datepicker -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"assets/vendors/datepicker/daterangepicker.css\">\r\n");
      out.write("<!-- begin::datepicker -->\r\n");
      out.write("\r\n");
      out.write("<!-- begin::vmap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/vendors/vmap/jqvmap.min.css\">\r\n");
      out.write("<!-- begin::vmap -->\r\n");
      out.write("\r\n");
      out.write("<!-- begin::custom styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/app.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/custom.css\" type=\"text/css\">\r\n");
      out.write("<!-- end::custom styles -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin::page loader-->\r\n");
      out.write("\t<div class=\"page-loader\">\r\n");
      out.write("\t\t<div class=\"spinner-border\"></div>\r\n");
      out.write("\t\t<span>Loading ...</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end::page loader -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin::sidebar -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<!-- end::sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin::side menu -->\r\n");
      out.write("\t<div class=\"side-menu\">\r\n");
      out.write("\t\t<div class='side-menu-body'>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"side-menu-divider\">Navigation</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-paint-bucket\"></i> <span>员工模块</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"EmpqueryMy\">我的信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"EmpqueryAllEmp\">查看员工</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"EmpqueryAllDept\"> <i class=\"icon ti-layout\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>部门事务</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"EmpqueryAllJob\"><i class=\"icon ti-rocket\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>职位管理</span> </a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <i class=\"icon ti-layers-alt\"></i> <span>文件</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"EmpqueryAllFile\">文件中心</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"FilequeryMyself\">我的文件</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"EmpqueryAllNo\"><i class=\"icon ti-layers-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>公告模块</span> </a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end::side menu -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin::navbar -->\r\n");
      out.write("\t<!-- end::navbar -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- begin::main content -->\r\n");
      out.write("\t<main class=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- begin::page header -->\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"page-header d-md-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<h4>Chat</h4>\r\n");
      out.write("\t\t\t\t<nav aria-label=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t<ol class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">Dashboard</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"breadcrumb-item\"><a href=\"#\">Apps</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"breadcrumb-item active\" aria-current=\"page\">Chat</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\tdata-target=\"#createEventModal\">\r\n");
      out.write("\t\t\t\t<i class=\"ti-comment m-r-5\"></i> New Chat\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end::page header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"card chat-app-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"row chat-app\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 chat-sidebar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-sidebar-search\">\r\n");
      out.write("\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Chat Search...\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-sidebar-messages\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-9 chat-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body-header\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-dark opacity-3 m-r-10 btn-chat-sidebar-open\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ti-menu\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<figure class=\"avatar avatar-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t</figure>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ml-auto d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"ml-2 btn btn-sm btn-success btn-floating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-video-camera\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown ml-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-sm  btn-warning btn-floating\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Block</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Delete</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"chat-body-messages\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"message-items\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 111111111111111111111111 -->\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 遍历集合 -->\r\n");
      out.write("\t\t\t\t\t\t\t");

								List<Message> messageList = (List<Message>) request.getAttribute("messageList");
								int r_id = Integer.parseInt(request.getAttribute("r_id").toString());
								int now_id = Integer.parseInt(request.getAttribute("now_id").toString());
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								for (int i = 0; i < messageList.size(); i++) {
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (messageList.get(i).getSend_id() == r_id) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(messageList.get(i).getContent());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"message-item-date text-muted\">");
      out.print(messageList.get(i).getTime());
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (messageList.get(i).getSend_id() == now_id) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-item outgoing-message\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(messageList.get(i).getContent());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"message-item-date text-muted\">");
      out.print(messageList.get(i).getTime());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(messageList.get(i).getState());
      out.write("</small>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 111111111111111111111111 -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end::main content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::global scripts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/bundle.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::global scripts -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::charts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/charts/chartjs/chart.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/charts/peity/jquery.peity.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/examples/charts/chartjs.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/examples/charts/peity.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script class=\"include\" type=\"text/javascript\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"assets/js/jquery.dcjqaccordion.2.7.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::charts -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::daterangepicker -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/datepicker/daterangepicker.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::daterangepicker -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::dashboard -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/examples/dashboard.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::dashboard -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::vamp -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/vmap/jquery.vmap.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/vmap/maps/jquery.vmap.usa.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/examples/vmap.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::vamp -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- begin::custom scripts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/app.js\"></script>\r\n");
      out.write("\t\t\t\t\t<!-- end::custom scripts -->\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/vendors/lightbox/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/examples/lightbox.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script src=\"https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t\t\t<script\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Emp_Info.jsp(123,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Emp_Info.jsp(123,7) ''",_jsp_getExpressionFactory().createValueExpression("",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Emp_Info.jsp(123,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("poster");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"EmpqueryByid\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tclass=\"list-group-item align-items-center d-flex list-group-item-action\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- 部门id --> <input type=\"hidden\" name=\"poster_id\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\tvalue=\"\"></br>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<figure class=\"avatar avatar-sm\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<img class=\"rounded-circle\" src=\"/Eimages/\"\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"...\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</figure>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<h6 class=\"m-0\"></h6>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div> <span class=\"badge badge-primary badge-pill ml-auto\">3</span>\r\n");
            out.write("\t\t\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
