/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2022-09-21 12:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/yueqian/作业/第二阶段项目/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Personnel_Management/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1663657070368L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 加入tablib的声明 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>menu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- begin::side menu -->\r\n");
      out.write("\t<div class=\"side-menu\">\r\n");
      out.write("\t\t<div class='side-menu-body'>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"side-menu-divider\">功能菜单</li>\r\n");
      out.write("\t\t\t\t<li class=\"\"><a href=\"#\"><i class=\"icon ti-home\"></i> <span>公司查询</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"\" href=\"index.html\">部门查询</a></li>     <!-- active -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dashboard-two.html\">职位查询</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dashboard-three.html\">公告查询</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- <li><a href=\"widgets.html\"><i class=\"icon ti-paint-bucket\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span>Widgets</span> <span class=\"badge bg-danger-gradient\">8+</span>\r\n");
      out.write("\t\t\t\t</a></li> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- layout-builder-toggle -->\r\n");
      out.write("\t\t\t\t<li><a data-attr=\"\" href=\"#\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon ti-layout\"></i> <span>员工管理</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"#\">Menu</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-horizontal-menu.html\">Horizontal</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-icon-menu.html\">Icon</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-dark-menu.html\">Dark</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-hidden-menu.html\">Hidden</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-container.html\">查询个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-dark.html\">修改个人信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"#\">Other</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-1.html\">Layout 1</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-2.html\">Layout 2</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-3.html\">Layout 3</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"layout-4.html\">Layout 4</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-rocket\"></i> <span>信息管理</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chat.html\">发送信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chat.html\">查询信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"#\">Email </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"inbox.html\">Inbox </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"read-email.html\">Email Read </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"compose-email.html\">Compose </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Calendar </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"calendar-basic.html\">Basic Calendar </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"external-dragging.html\">External Dragging\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"calendar-list.html\">Calendar List </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-layers-alt\"></i> <span>文件管理</span> </a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"alerts.html\">上传文件</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"badge.html\">查询下载文件</a></li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"buttons.html\">删除个人文件</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"pagination.html\">Pagination </a></li>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"dropdown.html\">Dropdown </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"accordion.html\">Accordion </a></li> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><a href=\"#\">Cards </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"basic-cards.html\">Basic Cards </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"image-cards.html\">Image Cards </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"card-scroll.html\">Card Scroll </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"other-cards.html\">Others </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"colors.html\">Colors </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"carousel.html\">Carousel </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tables.html\">Tables </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"tables.html\">Basic Tables </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"data-table.html\">Data Table </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"responsive-table.html\">Responsive Table </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"typography.html\">Typography </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"list-group.html\">List Group </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"media-object.html\">Media Object </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"avatar.html\">Avatars </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"images.html\">Images </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"progress.html\">Progrees </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"modal.html\">Modal </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"spinners.html\">Spinners </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"navs.html\">Navs </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tab.html\">Tab </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tooltip.html\">Tooltip </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"popovers.html\">Popovers </a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-paint-roller\"></i> <span>Advanced\r\n");
      out.write("\t\t\t\t\t\t\tUI</span> </a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"sweet-alert.html\">Sweet Alert </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"lightbox.html\">Light Box </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"toast.html\">Toast </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tour.html\">Tour </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"swiper.html\">Swiper </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"tree-view.html\">Tree View </a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-clipboard\"></i> <span>Forms</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"basic-form.html\">Basic Form </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"custom-form.html\">Custom Form </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"advanced-form.html\">Advanced Form </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"datepicker.html\">Datepicker </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"timepicker.html\">Timepicker </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"colorpicker.html\">Colorpicker </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-validation.html\">Form Validation </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-wizard.html\">Form Wizard </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"file-upload.html\">File Upload </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">CKEditor </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ckeditor-article.html\">Article Editor </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"ckeditor-inline.html\">Inline Editor </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"icons.html\"><i class=\"icon ti-crown\"></i> <span>Icons</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <i class=\"icon ti-map\"></i> <span>Maps</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"google-map.html\">Google</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"vector-map.html\">Vector</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"> <i class=\"icon ti-pie-chart\"></i> <span>Charts</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chart-chartjs.html\">Chartjs</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chart-justgage.html\">Justgage</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"chart-peity.html\">Peity</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-face-smile\"></i> <span>Authentication</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.html\">Login </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"register.html\">Register </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"recover-password.html\">Recovery Password </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"lock-screen.html\">Lock Screen </a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-files\"></i> <span>Pages</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"profile.html\">Profile </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"timeline.html\">Timeline </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"invoice.html\">Invoice </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pricing-table.html\">Pricing Table </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"search-result.html\">Search Result </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blank-page.html\">Blank Page V1 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blank-page-v2.html\">Blank Page V2 </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Errors </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"404.html\">404 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"404-alternative.html\">404 Alternative </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"mean-at-work.html\">Mean at Work </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon ti-menu\"></i> <span>Menu\r\n");
      out.write("\t\t\t\t\t\t\tLevel</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Menu Level </a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\">Menu Level </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end::side menu -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
